//
// This file was generated by the JPA Modeler
//
package co.modelo;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity

public class Auto implements Serializable {

    @Column(name = "fechaIngreso", nullable = false)
    @Temporal(TemporalType.DATE)
    @Basic
    private Date fechaIngreso;

    @Column(name = "potencia", nullable = false)
    @Basic
    private int potencia;

    @Column(name = "cilindraje", nullable = false)
    @Basic
    private int cilindraje;

    @OneToOne(targetEntity = Venta.class, mappedBy = "auto")
    private Venta venta;

    @Column(nullable = false)
    @Basic
    private int Modelo;

    @Column(name = "transmision", nullable = false)
    @Lob
    @Basic
    private String transmision;

    @Column(name = "matricula", unique = true, nullable = false)
    @Id
    private String matricula;

    @Column(name = "fabricante", nullable = false)
    @Basic
    private String fabricante;

    public Auto() {

    }

    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public int getPotencia() {
        return this.potencia;
    }

    public void setPotencia(int potencia) {
        this.potencia = potencia;
    }

    public int getCilindraje() {
        return this.cilindraje;
    }

    public void setCilindraje(int cilindraje) {
        this.cilindraje = cilindraje;
    }

    public Venta getVenta() {
        return this.venta;
    }

    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    public int getModelo() {
        return this.Modelo;
    }

    public void setModelo(int Modelo) {
        this.Modelo = Modelo;
    }

    public String getTransmision() {
        return this.transmision;
    }

    public void setTransmision(String transmision) {
        this.transmision = transmision;
    }

    public String getMatricula() {
        return this.matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    public String getFabricante() {
        return this.fabricante;
    }

    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + Objects.hashCode(this.matricula);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Auto other = (Auto) obj;
        if (!Objects.equals(this.matricula, other.matricula)) {
            return false;
        }
        return true;
    }

   

    @Override
    public String toString() {
        return "Auto{" + "matricula=" + matricula + '}';
    }

   
    
    
    
    
}
